title: DOCasCODE
optionalCategoryIndex: true
supportedLanguages: []
properties:
  - name: атрибу 1
    type: Flag
    style: dark-orange
    icon: alarm-clock
  - name: тр2
    type: Date
    style: dark-orange
    icon: arrow-up
style: pink-blue
logo: 1568625796_1568625746.png
logo_dark: 1568625796_1568625746.png
